### ISSUE TITLE
Sanitize SqlVariableName

### ISSUE THREAD

**Issue by grudolf** [docevaad/Chain#212] opened 2017-11-25 19:25 UTC
As currently there's no sanitizing of ColumnData.SqlVariableName, invalid SQL is generated for UPDATE, INSERT and WHERE statements for MSSQL if column names contain spaces (yeah, I know the names shouldn't contain spaces, but if they can, they do...)

```
exec sp_executesql 
N'UPDATE table SET [column name]=@column name WHERE [key column]=@key column;', 
N'@column name varchar(80),@key name varchar(4)',
@column name='123',
@key name='1234'
```

Surrounding parameter names with [] like in QuotedSqlName doesn't work, perhaps something similar to Utilities.ToClrName?

**Comment by Grauenwolf** [comment] 2017-11-25 23:47
Well that's a lovely kick to head.

Are you hitting that problem in production? If not, I'm going to wait until next weekend to fix it.

**Comment by Grauenwolf** [comment] 2017-11-26 06:56
I've checked in what I think is a working fix. It passes the obvious test cases, but I'm going to need to run all of the regression tests as it does touch the SQL generator. (Thankfully it doesn't affect the object materializer.)

There are now two modes for SQL generation. You can give it the ClrName (thanks @grudolf for the suggestion) or use the ColumnAttribute to give it the actual column name (SqlName).

If you have two properties, one with the ClrName and one with the SqlName, only one of them is going to get populated. I may be able to fix that by having the SQL generator return the same column twice, but really you shouldn't be doing that.

**Comment by Grauenwolf** [comment] 2017-11-26 06:57
Since I'm leaving on a trip Monday, I'll finish testing and push a build to NuGet next weekend.

**Comment by grudolf** [comment] 2017-11-26 08:03
Thanks. I'm just testing and not in a hurry, have a nice trip.

**Comment by Grauenwolf** [comment] 2017-12-11 04:53
Wow, this is trickier than I thought. I'm glad I added all of those regressions tests last year because I keep finding edge cases that the new code trips over. 

Hopefully this will be the last time we have to touch the SQL generator for awhile.

**Comment by Grauenwolf** [comment] 2017-12-11 05:44
Tortuga.Chain.Core.1.2.6553.38983

**Closed by Grauenwolf** 2017-12-11 05:44 UTC
Labels: bug, Core
